version: "3"
services:
  web:
    build: .
    volumes:
      - .:/InvoiceSystem
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123456
    volumes:
      - .:/InvoiceSystem/db
    ports:
      - "5432"