version: "3"
services:
  db:
    image: postgres
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=123456"
    ports:
      - "5432"

  web:
    build: .
    command: bundle exec rails s -p 3000
    volumes:
      - .:/InvoiceSystem
    ports:
      - "3000:3000"
    depends_on:
      - db